name: CD - Azure Git Push

on:
  # workflow_run:
  #   workflows: ["CT"]
  #   types:
  #     - completed
  push:
    branches:
      - main

jobs:
  deploy:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Push to Azure remote
        env:
          AZURE_REMOTE_URL: ${{ secrets.AZURE_REMOTE_URL }}
          AZURE_REMOTE_USER: ${{ secrets.AZURE_REMOTE_USER }}
          AZURE_REMOTE_PASSWORD: ${{ secrets.AZURE_REMOTE_PASSWORD }}
        run: |
          git remote add azure https://$AZURE_REMOTE_USER:$AZURE_REMOTE_PASSWORD@$AZURE_REMOTE_URL
          git push azure HEAD:master --force
