name: CD - macOS Release

on:
  workflow_run:
    workflows: ["CT"]
    types:
      - completed

jobs:
  build-macos:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip uninstall tensorflow
          pip install tensorflow-macos tensorflow-metal
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build macOS executable
        run: |
          pyinstaller --onefile --name "MNISTStreamlitApp" \
            --hidden-import streamlit \
            --collect-all streamlit \
            --collect-all blinker \
            --collect-all altair \
            src/app.py

        - name: Prepare release directory
          run: |
            mkdir -p release
            cp dist/MNISTStreamlitApp release/

      - name: Prepare release directory
        run: |
          mkdir -p release
          cp dist/MNISTStreamlitApp release/

      - name: Create or Update GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          files: release/MNISTStreamlitApp
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
