name: CT

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  retrain:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check if new data changed
        id: check_data
        run: |
            git fetch origin main
            CHANGED=$(git diff --name-only origin/main HEAD | grep '^data/new/' || true)
            if [ -z "$CHANGED" ]; then
              echo "No new data changes"
              exit 78  # GitHub Actions skips the job
            fi

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install --upgrade pip
      - run: pip install -r requirements.txt tensorflow
      - run: python src/continuous_training.py
      - run: ls -l model  # show updated model
