name: CT

on:
  # The single trigger: runs ONLY after the CI workflow completes.
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  continuous-training:
    # First condition: The job only runs if the CI workflow was successful.
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          # Check out the specific commit that triggered the CI workflow
          ref: ${{ github.event.workflow_run.head_sha }}

      # New step to check for file changes in the data directory
      - name: Check for changes in data directory
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: data/new/**

      - name: Set up Python
        # Second condition: This step (and all subsequent steps) will only run
        # if the previous 'changed-files' step found changes.
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt tensorflow

      - name: Run continuous training
        if: steps.changed-files.outputs.any_changed == 'true'
        run: python src/continuous_training.py

      - name: List model folder contents
        if: steps.changed-files.outputs.any_changed == 'true'
        run: ls -l model

